title: Logan Abraham
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "https://abe-mi.github.io" # the subpath of your site, e.g. /blog
url: "https://github.com/abe-mi/abe-mi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Logan Abraham # add your name
author-img: profilepic3-medium.png # add your photo
about-author: I am a developing data professional and Michigan State University graduate with a passion for leveraging data analytics to solve challenges, especially in sports. I focus on clean analysis, clear visuals, and effective communication of complex information. With a background in athletics and communication, I bring an adaptable, collaborative, and results-driven mindset to every project, thriving on turning data into actionable insights that drive impact.
 # add description
social-twitter: Abe242986 # add your Twitter handle
social-facebook: Logan Abraham # add your Facebook handle
social-github: abe-mi # add your Github handle
social-linkedin: logan-abraham24 # add your Linkedin handle
social-email: abrah196@msu.edu # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
